fix line height on advisory toggle
ObolNetwork/obol-ui pull request #113
Opened 2023-04-13 12:22 UTC by HananINouman

### Summary
Fixes the line height in the advisory toggle item. 

### Screenshots
<img width="574" alt="Screenshot 2023-04-13 at 3 21 23 PM" src="https://user-images.githubusercontent.com/110400366/231756597-12dbe696-72e8-4898-8300-164c199dcd93.png">

ticket: #427

2023-04-14 21:12 UTC, f1lander requested changes

2023-04-14 21:12 UTC, f1lander commented on package.json
> +    "ts-node": "^10.9.1",
why this is needed this pr?

2023-04-19 17:22 UTC, f1lander requested changes

2023-04-19 17:22 UTC, f1lander commented on package-lock.json
This files need to be removed, I guess you install by mistake using npm

2023-04-19 17:22 UTC, f1lander commented on yarn.lock
remove this change too, you need to remove the ts-node package using yarn remove -D `ts-node` the only change introduced for this PR needs to be the lineHeight

2023-04-20 08:34 UTC, HananINouman commented on yarn.lock
yes sorry by mistake

2023-04-20 08:37 UTC, HananINouman commented on yarn.lock
Got the error again once I removed yarn/lock changes, <img width="566" alt="Screenshot 2023-04-20 at 11 35 53 AM" src="https://user-images.githubusercontent.com/110400366/233309129-ae709c1e-6439-4cb4-b4cf-65483c42fc29.png">
Are we sure we need to install it globally but we added it to the launchpad package.json?

2023-04-28 04:34 UTC, f1lander commented on yarn.lock
Add it as dev-dep

2023-04-28 04:34 UTC, f1lander approved these changes
just add ts-node as dev-dep

2023-04-28 11:54 UTC, merged